# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_artifacts', '0002_artifactwhitelistitem'),
        ('fir_artifacts', '0003_auto_20160119_1131'),
    ]

    operations = [
    ]
