# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_artifacts', '0005_delete_artifactwhitelistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='value',
            field=models.TextField(),
        ),
    ]
