# Generated by Django 6.0.4 on 2026-04-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fir_artifacts", "0007_move_artifact_file_fields"),
        ("incidents", "0017_move_file_artifact_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="incidents",
            field=models.ManyToManyField(
                related_name="artifact_set",
                through="fir_artifacts.IncidentArtifact",
                to="incidents.incident",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.incident",
            ),
        ),
    ]
