# Dockerfile for FIR development instance
#
# build command:
#
# docker build -t redis [path_to_Dockerfile]
# docker run -it -p 6379:6379 --name fir_broker redis

FROM redis:3.2.5

CMD ["redis-server"]
