# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fir_artifacts', '0005_delete_artifactwhitelistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactEnrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('raw', models.TextField()),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_artifacts.Artifact')),
            ],
        ),
    ]
