# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_threatintel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yetiprofile',
            old_name='match_endpoint',
            new_name='endpoint',
        ),
        migrations.RemoveField(
            model_name='yetiprofile',
            name='observable_endpoint',
        ),
    ]
