# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_notifications', '0003_auto_20170127_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodconfiguration',
            name='key',
            field=models.CharField(choices=[(b'webhook', b'Webhook')], max_length=60, verbose_name='method'),
        ),
    ]
