# Generated by Django 5.2 on 2025-04-07 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_notifications', '0003_auto_20170127_1113'),
        ('incidents', '0014_alter_incident_date_alter_log_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodconfiguration',
            name='key',
            field=models.CharField(choices=[('email', 'Email')], max_length=60, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='business_lines',
            field=models.ManyToManyField(blank=True, related_name='+', to='incidents.businessline', verbose_name='business lines'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='business_lines',
            field=models.ManyToManyField(blank=True, related_name='+', to='incidents.businessline', verbose_name='business line'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('Event', [('event:commented', 'Event commented'), ('event:created', 'Event created'), ('event:status_changed', 'Event status changed'), ('event:updated', 'Event updated')]), ('Incident', [('incident:commented', 'Incident commented'), ('incident:created', 'Incident created'), ('incident:status_changed', 'Incident status changed'), ('incident:updated', 'Incident updated')])], max_length=60, verbose_name='event'),
        ),
        migrations.AlterUniqueTogether(
            name='methodconfiguration',
            unique_together={('user', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'event', 'method')},
        ),
        migrations.AddIndex(
            model_name='methodconfiguration',
            index=models.Index(fields=['user', 'key'], name='fir_notific_user_id_7fa73c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'event', 'method'], name='fir_notific_user_id_6291de_idx'),
        ),
    ]
