# Generated by Django 6.0.2 on 2026-02-08 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fir_notifications", "0004_alter_methodconfiguration_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="methodconfiguration",
            name="fir_notific_user_id_7fa73c_idx",
        ),
        migrations.RenameField(
            model_name="methodconfiguration",
            old_name="key",
            new_name="method",
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="event",
            field=models.CharField(
                choices=[
                    (
                        "Incident",
                        [
                            ("incident:commented", "Incident commented"),
                            ("incident:created", "Incident created"),
                            ("incident:status_changed", "Incident status changed"),
                            ("incident:updated", "Incident updated"),
                        ],
                    ),
                    (
                        "Event",
                        [
                            ("event:commented", "Event commented"),
                            ("event:created", "Event created"),
                            ("event:status_changed", "Event status changed"),
                            ("event:updated", "Event updated"),
                        ],
                    ),
                ],
                max_length=60,
                verbose_name="event",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="methodconfiguration",
            unique_together={("user", "method")},
        ),
        migrations.AddIndex(
            model_name="methodconfiguration",
            index=models.Index(
                fields=["user", "method"], name="fir_notific_user_id_111447_idx"
            ),
        ),
    ]
