# Generated by Django 6.0.2 on 2026-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fir_notifications",
            "0005_remove_methodconfiguration_fir_notific_user_id_7fa73c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="methodconfiguration",
            name="method",
            field=models.CharField(
                choices=[("email", "Email"), ("webhook", "Webhook")],
                max_length=60,
                verbose_name="method",
            ),
        ),
    ]
