# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_todos', '0005_auto_20160119_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolisttemplate',
            name='detection',
        ),
    ]
