# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-03 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_abuse', '0005_auto_20170102_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactenrichment',
            name='artifact',
        ),
        migrations.DeleteModel(
            name='ArtifactEnrichment',
        ),
    ]
