# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_nmapfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmapfile',
            name='host',
            field=models.CharField(max_length=20),
        ),
    ]
