# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0007_change_bl_base_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'access control entry',
                'verbose_name_plural': 'access control entries',
            },
        ),
        migrations.AlterModelOptions(
            name='businessline',
            options={'verbose_name': 'business line'},
        ),
        migrations.AddField(
            model_name='accesscontrolentry',
            name='business_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='incidents.BusinessLine', verbose_name='business line'),
        ),
        migrations.AddField(
            model_name='accesscontrolentry',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='accesscontrolentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
