# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_auto_20161101_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmapfile',
            name='scandate',
            field=models.CharField(max_length=10),
        ),
    ]
