# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_add_authz_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'permissions': (('handle_incidents', 'Can handle incidents'), ('report_events', 'Can report events'), ('view_incidents', 'Can view incidents'), ('view_statistics', 'Can view statistics'))},
        ),
    ]
