# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_auto_20161101_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='NessusFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scantime', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=20)),
                ('operatingOS', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=5)),
                ('protocol', models.CharField(max_length=10)),
                ('plugin_name', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=1)),
                ('risk', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=1024)),
                ('solution', models.CharField(max_length=1024)),
                ('existence', models.BooleanField()),
            ],
        ),
    ]
