# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-22 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_add_incicent_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
