# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-26 18:24
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_auto_20170122_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverityChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default=b'#777', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.SeverityChoice'),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.SeverityChoice'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.SeverityChoice'),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.SeverityChoice'),
        ),
    ]
