# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0010_auto_20170122_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[(b'O', 'Opened'), (b'QI', 'Qualification_in_progress'), (b'Q', 'Qualified'), (b'APD', 'AP_Defined'), (b'APV', 'AP_Validated'), (b'IN', 'In_progress'), (b'C', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='what',
            field=models.CharField(choices=[(b'O', 'Opened'), (b'QI', 'Qualification_in_progress'), (b'Q', 'Qualified'), (b'APD', 'AP_Defined'), (b'APV', 'AP_Validated'), (b'IN', 'In_progress'), (b'C', 'Closed')], max_length=100),
        ),
    ]
