# Generated by Django 3.1.6 on 2021-02-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_auto_20170122_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='action',
            field=models.ForeignKey(limit_choices_to={'group__name': 'action'}, on_delete=django.db.models.deletion.CASCADE, related_name='action_label', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='actor',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'actor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_label', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='confidentiality',
            field=models.IntegerField(choices=[(0, 'C0'), (1, 'C1'), (2, 'C2'), (3, 'C3')], default='1'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='detection',
            field=models.ForeignKey(limit_choices_to={'group__name': 'detection'}, on_delete=django.db.models.deletion.CASCADE, related_name='detection_label', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='plan',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'plan'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_label', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('B', 'Blocked')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='actor',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'actor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='detection',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'detection'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='plan',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'plan'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='severity',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='what',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('B', 'Blocked')], max_length=100),
        ),
    ]
