# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_auto_20170122_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='COA_requested_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='incident',
            name='COA_taken_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_assets',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='incident',
            name='categories',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='incident',
            name='confidence_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='incident',
            name='contact_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='containment_achieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='discovery_method_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='external_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='first_data_exfiltration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='first_malicious_action',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact_assessment_loss_estimation_CRYPTO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact_assessment_loss_estimation_USD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_discovery',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_reported',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='information_source_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='initial_compromise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='intended_effect_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='leveraged_TTP_resource_infrastructure_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_incident_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_indicator_TTP_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_indicator_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_indicator_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_observable_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='restoration_achieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='security_compromise_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='short_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='incident',
            name='threat_actor_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='incidenttemplate',
            name='short_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_incident',
            field=models.BooleanField(default=True),
        ),
    ]
