# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_auto_20170122_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confidentiality',
            field=models.IntegerField(choices=[(0, b'TLP:White'), (1, b'TLP:Green'), (2, b'TLP:Amber'), (3, b'TLP:Red')], default=3, verbose_name='security clearance'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='confidentiality',
            field=models.IntegerField(choices=[(0, b'TLP:White'), (1, b'TLP:Green'), (2, b'TLP:Amber'), (3, b'TLP:Red')], default=b'1'),
        ),
    ]
