# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_auto_20180110_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='confidentiality',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='plan',
        ),
    ]
