# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_auto_20180130_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='is_major',
        ),
    ]
