# Generated by Django 4.2.16 on 2024-11-11 16:04

from django.db import migrations, models
import django.db.models.deletion
import incidents.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_severitychoice_alter_incident_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='dynamic_config',
            field=models.JSONField(blank=True, default=dict, encoder=incidents.models.PrettyJSONEncoder),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'severity'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='severity', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='detection',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'detection'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.label'),
        ),
        migrations.AlterField(
            model_name='incidenttemplate',
            name='severity',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'severity'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.label'),
        ),
        migrations.DeleteModel(
            name='SeverityChoice',
        ),
    ]
