# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_remove_incident_is_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttemplate',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='incidenttemplate',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='incidenttemplate',
            name='plan',
        ),
    ]
