# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_auto_20180130_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='main_business_lines',
            field=models.ManyToManyField(related_name='incidents_affecting_main', to='incidents.BusinessLine'),
        ),
    ]
