# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_auto_20180201_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='concerned_business_lines',
            field=models.ManyToManyField(to='incidents.BusinessLine'),
        ),
    ]
