# Generated by Django 6.0.2 on 2026-02-17 17:18
import django.db.models.deletion
from django.db import migrations, models

import incidents.models


def create_severities_tlps_if_needed(apps, schema_editon):
    Incident = apps.get_model("incidents", "Incident")
    SeverityChoice = apps.get_model("incidents", "SeverityChoice")
    Tlp = apps.get_model("incidents", "Tlp")

    if Incident.objects.count() == 0:
        return

    if SeverityChoice.objects.count() == 0:
        SeverityChoice.objects.create(name="1", color="#468847")
        SeverityChoice.objects.create(name="2", color="#c8c800")
        SeverityChoice.objects.create(name="3", color="#f89406")
        SeverityChoice.objects.create(name="4", color="#f81920")

    if Tlp.objects.count() == 0:
        tlp_clear = Tlp.objects.create(name="CLEAR")
        tlp_green = Tlp.objects.create(name="GREEN")
        tlp_amber = Tlp.objects.create(name="AMBER")
        Tlp.objects.create(name="AMBER+STRICT")
        tlp_red = Tlp.objects.create(name="RED")

        # Migrate confidentialities. Convert C3 To TLP:RED instead of TLP:AMBER+STRICT
        Incident.objects.filter(confidentiality=3).update(confidentiality=tlp_red.id)
        Incident.objects.filter(confidentiality=2).update(confidentiality=tlp_amber.id)
        Incident.objects.filter(confidentiality=1).update(confidentiality=tlp_green.id)
        Incident.objects.filter(confidentiality=0).update(confidentiality=tlp_clear.id)


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0015_alter_severitychoice_name_incidentstatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tlp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(create_severities_tlps_if_needed),
        migrations.AlterField(
            model_name="incident",
            name="confidentiality",
            field=models.ForeignKey(
                default=incidents.models.get_initial_tlp,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="incidents.tlp",
            ),
        ),
        migrations.RenameField(
            model_name="incident",
            old_name="confidentiality",
            new_name="tlp",
        ),
    ]
