# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_auto_20180201_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
